#include <cstdio>
#include <cstdlib>
#include <format>
#include <iostream>
#include <utility>
#include <array>
#include <string_view>
#include <iterator>
#include <cassert>
#include <memory>
#include <cmath>
#include <vector>
#include <limits>
#include <random>
#include <type_traits>
#include <chrono>
#include <filesystem>
#include <cstring>
#include <string_view>
#include <optional>
#include <filesystem>

#include <glm/glm.hpp>
#include <glm/ext.hpp>
#include <SDL2/SDL.h>

#include "Format.h"
#include "Logging.h"
#include "DeleterFunc.h"
#include "ScopeExit.h"
#include "SmartPtr.h"
#include "SDLDefs.h"
#include "Utility.h"